apiVersion: v1
kind: Secret
metadata:
  name: serverroom-secret
  namespace: serverroom
type: Opaque
stringData:
  JWT_SECRET: "replace-with-random-secret"
  DATABASE_URL: "postgresql+psycopg2://serverroom:serverroom@postgres.serverroom.svc.cluster.local:5432/serverroom"
  POSTGRES_USER: "serverroom"
  POSTGRES_PASSWORD: "serverroom"
  POSTGRES_DB: "serverroom"
